<?php
/**
 * ShippingPackage
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ShippingPackage Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShippingPackage implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ShippingPackage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sequence_number' => 'int',
        'tracking_number' => 'string',
        'label_width' => 'int',
        'label_height' => 'int',
        'png_label_data_base64' => 'string',
        'pdf_bytes_documentation_base64' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sequence_number' => 'int32',
        'tracking_number' => null,
        'label_width' => 'int32',
        'label_height' => 'int32',
        'png_label_data_base64' => null,
        'pdf_bytes_documentation_base64' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sequence_number' => 'SequenceNumber',
        'tracking_number' => 'TrackingNumber',
        'label_width' => 'LabelWidth',
        'label_height' => 'LabelHeight',
        'png_label_data_base64' => 'PNGLabelDataBase64',
        'pdf_bytes_documentation_base64' => 'PDFBytesDocumentationBase64'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sequence_number' => 'setSequenceNumber',
        'tracking_number' => 'setTrackingNumber',
        'label_width' => 'setLabelWidth',
        'label_height' => 'setLabelHeight',
        'png_label_data_base64' => 'setPngLabelDataBase64',
        'pdf_bytes_documentation_base64' => 'setPdfBytesDocumentationBase64'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sequence_number' => 'getSequenceNumber',
        'tracking_number' => 'getTrackingNumber',
        'label_width' => 'getLabelWidth',
        'label_height' => 'getLabelHeight',
        'png_label_data_base64' => 'getPngLabelDataBase64',
        'pdf_bytes_documentation_base64' => 'getPdfBytesDocumentationBase64'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sequence_number'] = isset($data['sequence_number']) ? $data['sequence_number'] : null;
        $this->container['tracking_number'] = isset($data['tracking_number']) ? $data['tracking_number'] : null;
        $this->container['label_width'] = isset($data['label_width']) ? $data['label_width'] : null;
        $this->container['label_height'] = isset($data['label_height']) ? $data['label_height'] : null;
        $this->container['png_label_data_base64'] = isset($data['png_label_data_base64']) ? $data['png_label_data_base64'] : null;
        $this->container['pdf_bytes_documentation_base64'] = isset($data['pdf_bytes_documentation_base64']) ? $data['pdf_bytes_documentation_base64'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sequence_number
     *
     * @return int
     */
    public function getSequenceNumber()
    {
        return $this->container['sequence_number'];
    }

    /**
     * Sets sequence_number
     *
     * @param int $sequence_number sequence_number
     *
     * @return $this
     */
    public function setSequenceNumber($sequence_number)
    {
        $this->container['sequence_number'] = $sequence_number;

        return $this;
    }

    /**
     * Gets tracking_number
     *
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->container['tracking_number'];
    }

    /**
     * Sets tracking_number
     *
     * @param string $tracking_number tracking_number
     *
     * @return $this
     */
    public function setTrackingNumber($tracking_number)
    {
        $this->container['tracking_number'] = $tracking_number;

        return $this;
    }

    /**
     * Gets label_width
     *
     * @return int
     */
    public function getLabelWidth()
    {
        return $this->container['label_width'];
    }

    /**
     * Sets label_width
     *
     * @param int $label_width label_width
     *
     * @return $this
     */
    public function setLabelWidth($label_width)
    {
        $this->container['label_width'] = $label_width;

        return $this;
    }

    /**
     * Gets label_height
     *
     * @return int
     */
    public function getLabelHeight()
    {
        return $this->container['label_height'];
    }

    /**
     * Sets label_height
     *
     * @param int $label_height label_height
     *
     * @return $this
     */
    public function setLabelHeight($label_height)
    {
        $this->container['label_height'] = $label_height;

        return $this;
    }

    /**
     * Gets png_label_data_base64
     *
     * @return string
     */
    public function getPngLabelDataBase64()
    {
        return $this->container['png_label_data_base64'];
    }

    /**
     * Sets png_label_data_base64
     *
     * @param string $png_label_data_base64 png_label_data_base64
     *
     * @return $this
     */
    public function setPngLabelDataBase64($png_label_data_base64)
    {
        $this->container['png_label_data_base64'] = $png_label_data_base64;

        return $this;
    }

    /**
     * Gets pdf_bytes_documentation_base64
     *
     * @return string[]
     */
    public function getPdfBytesDocumentationBase64()
    {
        return $this->container['pdf_bytes_documentation_base64'];
    }

    /**
     * Sets pdf_bytes_documentation_base64
     *
     * @param string[] $pdf_bytes_documentation_base64 pdf_bytes_documentation_base64
     *
     * @return $this
     */
    public function setPdfBytesDocumentationBase64($pdf_bytes_documentation_base64)
    {
        $this->container['pdf_bytes_documentation_base64'] = $pdf_bytes_documentation_base64;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
