<?php
/**
 * CreateShippingLabelRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * CreateShippingLabelRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateShippingLabelRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateShippingLabelRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateShippingLabelRequest"
     */
    public function testCreateShippingLabelRequest()
    {
    }

    /**
     * Test attribute "rate_id"
     */
    public function testPropertyRateId()
    {
    }

    /**
     * Test attribute "shipment"
     */
    public function testPropertyShipment()
    {
    }

    /**
     * Test attribute "generate_hs_code"
     */
    public function testPropertyGenerateHsCode()
    {
    }

    /**
     * Test attribute "label_type"
     */
    public function testPropertyLabelType()
    {
    }
}
