<?php
/**
 * CustomsInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * CustomsInfoTest Class Doc Comment
 *
 * @category    Class
 * @description CustomsInfo
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomsInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustomsInfo"
     */
    public function testCustomsInfo()
    {
    }

    /**
     * Test attribute "customs_certify"
     */
    public function testPropertyCustomsCertify()
    {
    }

    /**
     * Test attribute "customs_signer"
     */
    public function testPropertyCustomsSigner()
    {
    }

    /**
     * Test attribute "contents_type"
     */
    public function testPropertyContentsType()
    {
    }

    /**
     * Test attribute "contents_explanation"
     */
    public function testPropertyContentsExplanation()
    {
    }

    /**
     * Test attribute "restriction_type"
     */
    public function testPropertyRestrictionType()
    {
    }

    /**
     * Test attribute "restriction_comments"
     */
    public function testPropertyRestrictionComments()
    {
    }

    /**
     * Test attribute "eel_pfc"
     */
    public function testPropertyEelPfc()
    {
    }

    /**
     * Test attribute "customs_items"
     */
    public function testPropertyCustomsItems()
    {
    }

    /**
     * Test attribute "declaration"
     */
    public function testPropertyDeclaration()
    {
    }

    /**
     * Test attribute "non_delivery_option"
     */
    public function testPropertyNonDeliveryOption()
    {
    }
}
