<?php
/**
 * GetShippingRateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetShippingRateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description GetShippingRateRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetShippingRateRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetShippingRateRequest"
     */
    public function testGetShippingRateRequest()
    {
    }

    /**
     * Test attribute "shipper_reference"
     */
    public function testPropertyShipperReference()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "transaction_src"
     */
    public function testPropertyTransactionSrc()
    {
    }

    /**
     * Test attribute "shipper"
     */
    public function testPropertyShipper()
    {
    }

    /**
     * Test attribute "send_from"
     */
    public function testPropertySendFrom()
    {
    }

    /**
     * Test attribute "send_to"
     */
    public function testPropertySendTo()
    {
    }

    /**
     * Test attribute "shipment_charge_type"
     */
    public function testPropertyShipmentChargeType()
    {
    }

    /**
     * Test attribute "service_code"
     */
    public function testPropertyServiceCode()
    {
    }

    /**
     * Test attribute "service_description"
     */
    public function testPropertyServiceDescription()
    {
    }

    /**
     * Test attribute "num_of_pieces"
     */
    public function testPropertyNumOfPieces()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "weight_unit"
     */
    public function testPropertyWeightUnit()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "dim_unit"
     */
    public function testPropertyDimUnit()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "label_type"
     */
    public function testPropertyLabelType()
    {
    }

    /**
     * Test attribute "label_format"
     */
    public function testPropertyLabelFormat()
    {
    }

    /**
     * Test attribute "customs_info"
     */
    public function testPropertyCustomsInfo()
    {
    }
}
