<?php
/**
 * GetShippingLabelResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetShippingLabelResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetShippingLabelResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetShippingLabelResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetShippingLabelResponse"
     */
    public function testGetShippingLabelResponse()
    {
    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {
    }

    /**
     * Test attribute "shipper_reference"
     */
    public function testPropertyShipperReference()
    {
    }

    /**
     * Test attribute "display_id"
     */
    public function testPropertyDisplayId()
    {
    }

    /**
     * Test attribute "shipment_id"
     */
    public function testPropertyShipmentId()
    {
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }

    /**
     * Test attribute "carrier_tracking_number"
     */
    public function testPropertyCarrierTrackingNumber()
    {
    }

    /**
     * Test attribute "carrier_local_tracking_number"
     */
    public function testPropertyCarrierLocalTrackingNumber()
    {
    }

    /**
     * Test attribute "carrier_tracking_url"
     */
    public function testPropertyCarrierTrackingUrl()
    {
    }

    /**
     * Test attribute "label_format"
     */
    public function testPropertyLabelFormat()
    {
    }

    /**
     * Test attribute "label_type"
     */
    public function testPropertyLabelType()
    {
    }

    /**
     * Test attribute "label_image"
     */
    public function testPropertyLabelImage()
    {
    }

    /**
     * Test attribute "label_url"
     */
    public function testPropertyLabelUrl()
    {
    }

    /**
     * Test attribute "warning"
     */
    public function testPropertyWarning()
    {
    }
}
