<?php
/**
 * LinnworksUserConfigResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * LinnworksUserConfigResponseTest Class Doc Comment
 *
 * @category    Class
 * @description LinnworksUserConfigResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LinnworksUserConfigResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LinnworksUserConfigResponse"
     */
    public function testLinnworksUserConfigResponse()
    {
    }

    /**
     * Test attribute "config_status"
     */
    public function testPropertyConfigStatus()
    {
    }

    /**
     * Test attribute "config_stage"
     */
    public function testPropertyConfigStage()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }

    /**
     * Test attribute "is_config_active"
     */
    public function testPropertyIsConfigActive()
    {
    }

    /**
     * Test attribute "is_error"
     */
    public function testPropertyIsError()
    {
    }
}
