<?php
/**
 * LinnworksUserConfigItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * LinnworksUserConfigItemTest Class Doc Comment
 *
 * @category    Class
 * @description LinnworksUserConfigItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LinnworksUserConfigItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LinnworksUserConfigItem"
     */
    public function testLinnworksUserConfigItem()
    {
    }

    /**
     * Test attribute "list_values"
     */
    public function testPropertyListValues()
    {
    }

    /**
     * Test attribute "value_type"
     */
    public function testPropertyValueType()
    {
    }

    /**
     * Test attribute "config_item_id"
     */
    public function testPropertyConfigItemId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "group_name"
     */
    public function testPropertyGroupName()
    {
    }

    /**
     * Test attribute "sort_order"
     */
    public function testPropertySortOrder()
    {
    }

    /**
     * Test attribute "selected_value"
     */
    public function testPropertySelectedValue()
    {
    }

    /**
     * Test attribute "reg_ex_validation"
     */
    public function testPropertyRegExValidation()
    {
    }

    /**
     * Test attribute "reg_ex_error"
     */
    public function testPropertyRegExError()
    {
    }

    /**
     * Test attribute "must_be_specified"
     */
    public function testPropertyMustBeSpecified()
    {
    }

    /**
     * Test attribute "read_only"
     */
    public function testPropertyReadOnly()
    {
    }
}
