<?php
/**
 * PackageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PackageTest Class Doc Comment
 *
 * @category    Class
 * @description Package
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PackageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Package"
     */
    public function testPackage()
    {
    }

    /**
     * Test attribute "sequence_number"
     */
    public function testPropertySequenceNumber()
    {
    }

    /**
     * Test attribute "package_weight"
     */
    public function testPropertyPackageWeight()
    {
    }

    /**
     * Test attribute "package_width"
     */
    public function testPropertyPackageWidth()
    {
    }

    /**
     * Test attribute "package_height"
     */
    public function testPropertyPackageHeight()
    {
    }

    /**
     * Test attribute "package_depth"
     */
    public function testPropertyPackageDepth()
    {
    }

    /**
     * Test attribute "package_format"
     */
    public function testPropertyPackageFormat()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }
}
