<?php
/**
 * ProductsRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ProductsRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ProductsRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductsRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductsRequest"
     */
    public function testProductsRequest()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "origin_country"
     */
    public function testPropertyOriginCountry()
    {
    }

    /**
     * Test attribute "attribute1"
     */
    public function testPropertyAttribute1()
    {
    }

    /**
     * Test attribute "attribute2"
     */
    public function testPropertyAttribute2()
    {
    }

    /**
     * Test attribute "attribute3"
     */
    public function testPropertyAttribute3()
    {
    }

    /**
     * Test attribute "attribute4"
     */
    public function testPropertyAttribute4()
    {
    }

    /**
     * Test attribute "attribute5"
     */
    public function testPropertyAttribute5()
    {
    }

    /**
     * Test attribute "attribute6"
     */
    public function testPropertyAttribute6()
    {
    }

    /**
     * Test attribute "hs_code_us"
     */
    public function testPropertyHsCodeUs()
    {
    }

    /**
     * Test attribute "current_price"
     */
    public function testPropertyCurrentPrice()
    {
    }

    /**
     * Test attribute "product_url"
     */
    public function testPropertyProductUrl()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "skn"
     */
    public function testPropertySkn()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "ship_alone"
     */
    public function testPropertyShipAlone()
    {
    }

    /**
     * Test attribute "delete"
     */
    public function testPropertyDelete()
    {
    }

    /**
     * Test attribute "weight_unit"
     */
    public function testPropertyWeightUnit()
    {
    }

    /**
     * Test attribute "dim_unit"
     */
    public function testPropertyDimUnit()
    {
    }

    /**
     * Test attribute "battery_type"
     */
    public function testPropertyBatteryType()
    {
    }
}
