<?php
/**
 * QuoteRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * QuoteRequestTest Class Doc Comment
 *
 * @category    Class
 * @description QuoteRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "QuoteRequest"
     */
    public function testQuoteRequest()
    {
    }

    /**
     * Test attribute "item_details_list"
     */
    public function testPropertyItemDetailsList()
    {
    }

    /**
     * Test attribute "address_info"
     */
    public function testPropertyAddressInfo()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "customs_duty"
     */
    public function testPropertyCustomsDuty()
    {
    }

    /**
     * Test attribute "insurance"
     */
    public function testPropertyInsurance()
    {
    }

    /**
     * Test attribute "service_level"
     */
    public function testPropertyServiceLevel()
    {
    }

    /**
     * Test attribute "order_reference"
     */
    public function testPropertyOrderReference()
    {
    }

    /**
     * Test attribute "other_discount"
     */
    public function testPropertyOtherDiscount()
    {
    }

    /**
     * Test attribute "other_discount_currency"
     */
    public function testPropertyOtherDiscountCurrency()
    {
    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {
    }

    /**
     * Test attribute "always_quote"
     */
    public function testPropertyAlwaysQuote()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }

    /**
     * Test attribute "promo_code"
     */
    public function testPropertyPromoCode()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "dim_unit"
     */
    public function testPropertyDimUnit()
    {
    }

    /**
     * Test attribute "weight_unit"
     */
    public function testPropertyWeightUnit()
    {
    }

    /**
     * Test attribute "shipping_value"
     */
    public function testPropertyShippingValue()
    {
    }

    /**
     * Test attribute "shipping_value_currency"
     */
    public function testPropertyShippingValueCurrency()
    {
    }

    /**
     * Test attribute "track_by_email"
     */
    public function testPropertyTrackByEmail()
    {
    }
}
