<?php
/**
 * ServiceLevelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ServiceLevelTest Class Doc Comment
 *
 * @category    Class
 * @description ServiceLevel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceLevelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServiceLevel"
     */
    public function testServiceLevel()
    {
    }

    /**
     * Test attribute "service_level_id"
     */
    public function testPropertyServiceLevelId()
    {
    }

    /**
     * Test attribute "service_code"
     */
    public function testPropertyServiceCode()
    {
    }

    /**
     * Test attribute "service_name"
     */
    public function testPropertyServiceName()
    {
    }

    /**
     * Test attribute "shipping_charge"
     */
    public function testPropertyShippingCharge()
    {
    }

    /**
     * Test attribute "duty"
     */
    public function testPropertyDuty()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "insurance"
     */
    public function testPropertyInsurance()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "company_currency"
     */
    public function testPropertyCompanyCurrency()
    {
    }

    /**
     * Test attribute "shipping_charge_company_currency_value"
     */
    public function testPropertyShippingChargeCompanyCurrencyValue()
    {
    }

    /**
     * Test attribute "duty_company_currency_value"
     */
    public function testPropertyDutyCompanyCurrencyValue()
    {
    }

    /**
     * Test attribute "tax_company_currency_value"
     */
    public function testPropertyTaxCompanyCurrencyValue()
    {
    }

    /**
     * Test attribute "insurance_company_currency_value"
     */
    public function testPropertyInsuranceCompanyCurrencyValue()
    {
    }

    /**
     * Test attribute "subtotal_company_currency_value"
     */
    public function testPropertySubtotalCompanyCurrencyValue()
    {
    }

    /**
     * Test attribute "promo_discount"
     */
    public function testPropertyPromoDiscount()
    {
    }

    /**
     * Test attribute "promo_discount_company_currency"
     */
    public function testPropertyPromoDiscountCompanyCurrency()
    {
    }

    /**
     * Test attribute "handling"
     */
    public function testPropertyHandling()
    {
    }

    /**
     * Test attribute "invalid_items"
     */
    public function testPropertyInvalidItems()
    {
    }
}
