<?php
/**
 * TrackShipmentResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * TrackShipmentResponseTest Class Doc Comment
 *
 * @category    Class
 * @description TrackShipmentResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TrackShipmentResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TrackShipmentResponse"
     */
    public function testTrackShipmentResponse()
    {
    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {
    }

    /**
     * Test attribute "shipper_reference"
     */
    public function testPropertyShipperReference()
    {
    }

    /**
     * Test attribute "display_id"
     */
    public function testPropertyDisplayId()
    {
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }

    /**
     * Test attribute "carrier_tracking_number"
     */
    public function testPropertyCarrierTrackingNumber()
    {
    }

    /**
     * Test attribute "carrier_local_tracking_number"
     */
    public function testPropertyCarrierLocalTrackingNumber()
    {
    }

    /**
     * Test attribute "carrier_tracking_url"
     */
    public function testPropertyCarrierTrackingUrl()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "weight_unit"
     */
    public function testPropertyWeightUnit()
    {
    }

    /**
     * Test attribute "consignee_address"
     */
    public function testPropertyConsigneeAddress()
    {
    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {
    }

    /**
     * Test attribute "warning"
     */
    public function testPropertyWarning()
    {
    }
}
