<?php
/**
 * UpsLiveRatesSettingsDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipping Label API
 *
 * Shipping Label application
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * UpsLiveRatesSettingsDataTest Class Doc Comment
 *
 * @category    Class
 * @description UpsLiveRatesSettingsData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpsLiveRatesSettingsDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpsLiveRatesSettingsData"
     */
    public function testUpsLiveRatesSettingsData()
    {
    }

    /**
     * Test attribute "additional_info"
     */
    public function testPropertyAdditionalInfo()
    {
    }

    /**
     * Test attribute "request_option"
     */
    public function testPropertyRequestOption()
    {
    }

    /**
     * Test attribute "pickup_type"
     */
    public function testPropertyPickupType()
    {
    }

    /**
     * Test attribute "negotiated_rates_indicator"
     */
    public function testPropertyNegotiatedRatesIndicator()
    {
    }

    /**
     * Test attribute "customer_classification"
     */
    public function testPropertyCustomerClassification()
    {
    }

    /**
     * Test attribute "shipment_indication_type"
     */
    public function testPropertyShipmentIndicationType()
    {
    }

    /**
     * Test attribute "service_additional_descriptions"
     */
    public function testPropertyServiceAdditionalDescriptions()
    {
    }
}
